name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    permissions:
      contents: read
      actions: none
      checks: none
      deployments: none
      issues: none
      packages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none

    steps:
      - name: Pull latest code from main
        run: |
          cd /home/sac/Intern
          git reset --hard
          git pull origin main

      - name: Install dependencies
        run: |
          cd /home/sac/Intern/my-app
          npm install

      - name: Build app
        run: |
          cd /home/sac/Intern/my-app
          npm run build

      - name: Restart PM2
        run: |
          pm2 restart intern
